version: '3.1'

services:
  statistic-server:
    build: stateService/httpService
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    restart: always
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=GMT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d stats-db"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network

  service:
    build: main-server
    container_name: main-server
    depends_on:
      - statistic-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
    networks:
      - app-network

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=GMT
    networks:
      - app-network

networks:
  app-network:
    driver: bridge