CREATE TABLE IF NOT EXISTS PUBLIC.categories (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_categories_id PRIMARY KEY (id),
    CONSTRAINT un_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS PUBLIC.users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(250) NOT NULL,
    email                 VARCHAR(254) NOT NUll,
    CONSTRAINT pk_users_id PRIMARY KEY(id),
    CONSTRAINT un_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS PUBLIC.events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation           VARCHAR(2000) NOT NULL,
    category_id          BIGINT NOT NULL,
    confirmed_requests   BIGINT,
    created_on           TIMESTAMP WITHOUT TIME ZONE,
    description          VARCHAR(7000) NOT NULL,
    event_date           TIMESTAMP WITHOUT TIME ZONE,
    initiator_id         BIGINT NOT NULL,
    lat                  FLOAT NOT NULL,
    lon                  FLOAT NOT NULL,
    paid                 BOOLEAN NOT NULL,
    participant_limit    BIGINT NOT NUll,
    published_on         TIMESTAMP WITHOUT TIME ZONE,
    request_moderation   VARCHAR NOT NULL,
    state                VARCHAR NOT NULL,
    title                VARCHAR(120) NOT NULL,
    views                BIGINT,
    CONSTRAINT pk_events_id PRIMARY KEY(id),
    CONSTRAINT fk_categories_id FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT fk_initiator_id FOREIGN KEY(initiator_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.compilations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned                VARCHAR(255) NOT NULL,
    title                 VARCHAR(51) NOT NULL,
    CONSTRAINT pk_compilation_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.participation_requests(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created               TIMESTAMP WITHOUT TIME ZONE,
    event                 BIGINT NOT NULL,
    requester	          BIGINT NOT NULL,
    status                VARCHAR NOT NULL,
    CONSTRAINT pk_participation_requests_id PRIMARY KEY(id),
    CONSTRAINT fk_participation_requests_events_id FOREIGN KEY(event) REFERENCES events(id),
    CONSTRAINT fk_participation_requests_requester_id FOREIGN KEY(requester) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.comments (
	id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id               BIGINT NOT NULL,
	event_id              BIGINT NOT NULL,
	text_comment          TEXT NOT NULL,
	state                 VARCHAR NOT NULL,
	created_on            TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (id),
	CONSTRAINT comments_users_fk FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT comments_events_fk FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS PUBLIC.compilations_events(
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,
    CONSTRAINT pk_compilations_events PRIMARY KEY(compilation_id, event_id),
    CONSTRAINT fk_compilation_id FOREIGN KEY(compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_id FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT un_events_compilation UNIQUE (compilation_id, event_id)
);


